receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlphttp/seq:
    endpoint: http://seq:5341/ingest/otlp
    headers:
      "X-Seq-ApiKey": "Yx9lqBz4ehJGIgDoSxzp"
    tls:
      insecure: false
  otlp/elasticsearchlocal:
    endpoint: "apm-server:8200"
    headers:
      Authorization: "Bearer v5vkr9aSIZe24j7GB1"
    tls:
      insecure: true
  influxdb:
    endpoint: http://influxdb:8086
    token: yNlPzWC74VvgmYjSzJchrdqi8bTlunaBopiZoS8QLOBUz_F42tPYDEbbdJ5hcZLhzrnMX98z2fFJa5HeN5Bsyg==
    org: test
    bucket: ai

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

extensions:
  zpages:
    endpoint: :55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlp/jaeger, otlp/elasticsearchlocal]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/seq, otlp/elasticsearchlocal]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, influxdb, otlp/elasticsearchlocal]